### ISSUE TITLE
https images cant be resized

### ISSUE THREAD

**Issue by markrambow** [sdepold/node-imageable#1]
The problem is with your identify command

identify -format  'https://dawandaimages.s3.amazonaws.com/Product/12842/12842046/listview/1285335354-713.jpg'

but: 
$ identify -format %m 'http://dawandaimages.s3.amazonaws.com/Product/12842/12842046/listview/1285335354-713.jpg'
JPEG

%m does not work here

For resizing an Image you do 3 requests
1. head to check existing
2. identify
3. convert

I recommend downloading once, do identify and convert would do the trick much faster.
Identify is also only necessary when no .jpg or similar is in the url

Cheers
Mark

**Comment by sdepold** [comment]
fixed
