### ISSUE TITLE
Cache not working on localhost

### ISSUE THREAD

**Issue by ghost** [sdepold/node-imageable#13]
Hi,

Thank you for an extremely easy solution to image manipulation for node.js

I'm using imageable in one of my apps and I've tried to set up caching but with no success so far.

Here is what my config file looks like - username and appdirectory are placeholder for my account and application directory. 

However, no photo gets cached in the directory tmp/imageable. Any suggestions what I might be doing wrong? I've set up all permissions for the directory tmp/imageable. 

 {
  "namespace":    "",
  "maxListeners": 512,
  "imageSizeLimit": 1024,
  "timeouts": {
    "convert": 5000,
    "identify": 100,
    "download": 1000
  },
  "whitelist": {
    "allowedHosts": ["._google.com", "._facebook.com", "._localhost", "._goeassy.herokuapp.com"],
    "trustedHosts": ["._google.com", "._localhost", ".*goeassy.herokuapp.com"]
  },
  "keepDownloads": true,
  "maxDownloadCacheSize": 30000,
  "tmpPathRoot": "/Users/username/appdirectory/tmp/imageable"
}

**Comment by sdepold** [comment]
Are the images removed directly after the image was processed?  

Am Montag, 17. September 2012 um 20:11 schrieb Ovidiu Spatacian-Tarnu:

**Comment by zooshme** [comment]
Thank you for your promp reply Sascha. I'm not sure I understand your question. 

The images don't seem to be downloaded at all in the tmp/imageable folder.

**Comment by zooshme** [comment]
This is what is use to generate the images <img src="http://localhost:3000/fit/lesson-poster.jpeg?url=http://localhost:3000/uploads/images/snow-1347800278949.jpg&amp;size=300x300">

**Comment by zooshme** [comment]
``` html
<img src="http://localhost:3000/fit/lesson-poster.jpeg?url=http://localhost:3000/uploads/images/snow-1347800278949.jpg&amp;size=300x300">
```

**Comment by sdepold** [comment]
Ah :) ok :)

I guess u misses either the hash or the magic key. Check the docs of
node-imageable. The default is "magic". So your url should be smth like

<img src="http://localhost:3000/fit/magic/lesson-poster.jpeg?url=http://localhost:3000/uploads/images/snow-1347800278949.jpg&amp;size=300x300">

Am 17.09.2012 um 21:47 schrieb Ovidiu Spatacian-Tarnu <
notifications@github.com>:

<img src="http://localhost:3000/fit/lesson-poster.jpeg?url=http://localhost:3000/uploads/images/snow-1347800278949.jpg&amp;size=300x300">

 —
Reply to this email directly or view it on
GitHubhttps://github.com/dawanda/node-imageable/issues/13#issuecomment-8628325.

**Comment by zooshme** [comment]
Thank you Sascha. I've added the hash to the url but still nothing happens. I really don't know what I'm doing wrong. Could it be a bug in node.js/express.js?

**Comment by zooshme** [comment]
I've just deleted the imageable folder from node_modules and run nom install again. Caching seems to be working ok now. Thank you for your help Sascha.

**Comment by sdepold** [comment]
It's possible that u didn't have v0.10.0!?

Am 18.09.2012 um 02:13 schrieb Ovidiu Spatacian-Tarnu <
notifications@github.com>:

I've just deleted the imageable folder from node_modules and run nom
install again. Caching seems to be working ok now. Thank you for your help
Sascha.

On 17 Sep 2012, at 21:09, Sascha Depold notifications@github.com wrote:

> Ah :) ok :)
> 
> I guess u misses either the hash or the magic key. Check the docs of
> node-imageable. The default is "magic". So your url should be smth like
> 
> <img src="
> http://localhost:3000/fit/magic/lesson-poster.jpeg?url=http://localhost:3000/uploads/images/snow-1347800278949.jpg&amp;size=300x300">
> 
> Am 17.09.2012 um 21:47 schrieb Ovidiu Spatacian-Tarnu <
> notifications@github.com>:
> 
> <img src="
> http://localhost:3000/fit/lesson-poster.jpeg?url=http://localhost:3000/uploads/images/snow-1347800278949.jpg&amp;size=300x300">
> 
> —
> Reply to this email directly or view it on
> GitHub<
> https://github.com/dawanda/node-imageable/issues/13#issuecomment-8628325>.
> —
> Reply to this email directly or view it on GitHub.

—
Reply to this email directly or view it on
GitHubhttps://github.com/dawanda/node-imageable/issues/13#issuecomment-8635541.
